#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running npm build before push..."
npm run build
if [ $? -ne 0 ]; then
    echo "Build failed. Aborting push."
    exit 1
fi

echo "Build successful. Proceeding with push."
